/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.duan.java.views;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author macbookprom1
 */
public class CategoriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoriesPanel
     */
    
    private JPanel mainPanel;  // khai báo => null
    
    public CategoriesPanel() {
        initComponents();
    }
    
    public CategoriesPanel(JPanel mainPanel) {
        initComponents();
        this.mainPanel = mainPanel;
    }
    
//    public void setMainPanel(JPanel mainPanel){
//        this.mainPanel = mainPanel;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddCat = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setText("Categories");

        btnAddCat.setText("Thêm danh mục");
        btnAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddCat)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCat)
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatActionPerformed
        // TODO add your handling code here:
        
        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "ADD_CATEGORIES_PANEL");
    }//GEN-LAST:event_btnAddCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
